version: '3.8'

networks:
  Multichain-Network:
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.1.0/24

services:
  genesis:
    build: 
      context: ./createGenesis
      dockerfile: Docker
    container_name: multichain-genesis
    networks:
      Multichain-Network:
        ipv4_address: 192.168.1.3
    volumes:
      - ./genesis:/root/.multichain
    ports:
      - "6010:6010"
      - "6011:6011"
      - "6012:6012"
    entrypoint: ["sh", "-c", "python3 genesisInit.py" , "tail -f /dev/null"]


  node1:
    build: 
      context: ./createNode
      dockerfile: Docker
    container_name: multichain-node1
    networks:
      Multichain-Network:
        ipv4_address: 192.168.1.4
    volumes:
      - ./node1:/root/.multichain
    ports:
      - "6020:6020"
      - "6021:6021"
      - "6022:6022"
    entrypoint: ["bash", "-c", "tail -f /dev/null"]