# version: '3.8'

volumes:
  genesis:
  node1:

networks:
  test:
    name: multichain_test

services:

  genesis:
    build:
      context: ./createGenesis
      dockerfile: Docker
    container_name: multichain_genesis
    networks:
      - test
    volumes:
      - ../multichain/genesis_data:/root/.multichain
    # privileged: true
    working_dir: /root
    ports:
      - 7010:7010
      - 7011:7011
    entrypoint: ["sh", "-c", "tail -f /dev/null"]

  node1:
    build:
      context: ./createNode
      dockerfile: Docker
    container_name: multichain_node1
    networks:
      - test
    depends_on:
      - genesis
    volumes:
      - ../multichain/node1_data:/root/.multichain
    # privileged: true
    working_dir: /root
    ports:
      - 7020:7020
      - 7021:7021
    entrypoint: ["sh", "-c", "tail -f /dev/null"]