# version: '3.8'

volumes:
  genesis:
  node1:
  node2:

networks:
  mcNet:
    name: mcNEt

services:
  genesis:
    hostname: genesis
    build:
      context: ./createFiles
      dockerfile: Docker
    container_name: lc_genesis
    networks:
      - mcNet
    volumes:
      - ../multichain/genesis_data:/root/.multichain
    # privileged: true
    # working_dir: /root
    ports:
      - 7010:7010
      - 7011:7011
    entrypoint: ["sh", "-c", "python3 ./createFiles/genesis.py && touch /root/done && tail -f /dev/null"]
# python3 genesis.py && 
    # wait for genesis to finish
    healthcheck: 
      test: ["CMD", "test", "-f", "/root/done"]
      interval: 5s
      retries: 20
      start_period: 5s
      timeout: 3s

  node1:
    hostname: node1
    build:
      context: ./createFiles
      dockerfile: Docker
    container_name: multichain_node1
    networks:
      - mcNet
    depends_on:
      genesis:
        condition: service_healthy
    volumes:
      - ../multichain/node1_data:/root/.multichain
    ports:
      - 7020:7020
      - 7021:7021
    entrypoint: ["sh", "-c", "python3 node.py && touch /root/done && tail -f /dev/null"]
    # python3 node.py &&
    # wait for node to finish
    healthcheck: 
      test: ["CMD", "test", "-f", "/root/done"]
      interval: 5s
      retries: 20
      start_period: 5s
      timeout: 3s

  node2:
    hostname: node2
    build:
      context: ./createFiles
      dockerfile: Docker
    container_name: multichain_node2
    networks:
      - mcNet
    depends_on:
      node1:
        condition: service_healthy
    volumes:
      - ../multichain/node2_data:/root/.multichain
    ports:
    - 7030:7030
    - 7031:7031
    entrypoint: ["sh", "-c", "python3 ./createFiles/node.py && touch /root/done && tail -f /dev/null"]
    # python3 node.py &&