version: '3.8'

networks:
  Multichain-Network:
    driver: overlay
    attachable: true
    ipam:
      config:
        - subnet: 192.168.1.0/24

services:
  genesis:
    build: 
      context: ./createGenesis
      dockerfile: Docker
    container_name: multichain-genesis
    networks:
      Multichain-Network:
        ipv4_address: 192.168.1.10
    # volumes:
    #   - ./genesis:/root/.multichain
    ports:
      - "6001:6001"
      - "6002:6002"
      - "6003:6003"
    entrypoint: ["sh", "-c", "python3 genesisInit.py && tail -f /dev/null"]


  node1:
    build: 
      context: ./createNode
      dockerfile: Docker
    container_name: multichain-node1
    networks:
      Multichain-Network:
        ipv4_address: 192.168.1.11
    # volumes:
    #   - ./node1:/root/.multichain
    ports:
      - "6004:6004"
      - "6005:6005"
      - "6006:6006"
    entrypoint: ["bash", "-c", "tail -f /dev/null"]