# version: '3.8'

volumes:
  genesis:
  node1:
  node2:

networks:
  test:
    name: multichain_test

services:

  genesis:
    build:
      context: ./createGenesis
      dockerfile: Docker
    container_name: multichain_genesis
    networks:
      - test
    volumes:
      - ../multichain/genesis_data:/root/.multichain
    # privileged: true
    # working_dir: /root
    ports:
      - 7010:7010
      - 7011:7011
    entrypoint: ["sh", "-c", "python3 genesis.py && touch /root/genesis_done && tail -f /dev/null"]
# python3 genesis.py && 
    # wait for genesis to finish
    healthcheck: 
      test: ["CMD", "test", "-f", "/root/genesis_done"]
      interval: 5s
      retries: 20
      start_period: 5s
      timeout: 3s

  node1:
    build:
      context: ./createNode
      dockerfile: Docker
    container_name: multichain_node1
    networks:
      - test
    depends_on:
      genesis:
        condition: service_healthy
    volumes:
      - ../multichain/node1_data:/root/.multichain
    ports:
      - 7020:7020
      - 7021:7021
    entrypoint: ["sh", "-c", "python3 node.py && tail -f /dev/null"]
    # python3 node.py &&

    node2:
      build:
        context: ./createNode
        dockerfile: Docker
      container_name: multichain_node2
      networks:
        - test
      depends_on:
        genesis:
          condition: service_healthy
      volumes:
        - ../multichain/node1_data:/root/.multichain
      ports:
      - 7030:7030
      - 7031:7031
      entrypoint: ["sh", "-c", "python3 node.py && tail -f /dev/null"]
    # python3 node.py &&